meta_product_name: "Buzz Reads"
meta_title: "Buzz Reads - allows children to join their classes and access reading material from anywhere, all while interacting with their teachers and classmates."
meta_description: "Guided reading app"
meta_image: "cover.png" # should exist in `app/assets/images/`
