meta_product_name: "Buzz Reads"
meta_title: "Buzz Reads - Connecting teachers and students via guided reading."
meta_description: "Guided reading app, allows children to join their classes and access reading material from anywhere, all while interacting with their teachers and classmates."
meta_image: "ms-icon-310x310.png" # should exist in `app/assets/images/`
